---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: orderaccuracy
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/east-fl-orl-722/orderaccuracy
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
