apiVersion: v1
kind: Service
metadata:
  name: dogs-cats
  namespace: dogs-cats
spec:
  selector:
    app: dogs-cats
  type: NodePort
  ports:
    - name: node-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30088
