apiVersion: v1
kind: Service
metadata:
  name: orderaccuracy
  namespace: orderaccuracy
spec:
  selector:
    app: orderaccuracy
  type: NodePort
  ports:
    - name: node-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
