apiVersion: v1
kind: Service
metadata:
  name: imdb
  namespace: imdb
spec:
  selector:
    app: imdb
  type: NodePort
  ports:
    - name: nodePort
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
