apiVersion: v1
kind: Service
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
spec:
  selector:
    app: {{gitops.app}}
  type: NodePort
  ports:
    - name: node-port
      protocol: TCP
      port: {{gitops.port}}
      targetPort: {{gitops.port}}
      nodePort: {{gitops.nodePort}}
